# Generated by Django 5.1.4 on 2024-12-19 05:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceprovider",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="serviceprovider",
            name="longitude",
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
