# Generated by Django 5.1.4 on 2024-12-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_servicecategory_icon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otp",
            old_name="created_at",
            new_name="created",
        ),
    ]
