# Generated by Django 5.1.4 on 2024-12-27 11:00

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_rename_created_at_otp_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="created_at",
            field=models.DateTimeField(default=now),
            preserve_default=False,
        ),
    ]
