# Generated by Django 5.1.4 on 2024-12-27 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_servicecategory_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="refund",
            name="refunded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="tempuser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
