# Generated by Django 5.1.4 on 2024-12-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_otp_created_alter_refund_refunded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
