# Generated by Django 5.1.4 on 2024-12-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_booking_is_deleted_payment_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
