# Generated by Django 5.1.4 on 2024-12-31 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_serviceprovider_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
